import { test, expect } from "@playwright/test";
import { uniquePrefix, proxyGet } from "../../../helpers/kong";
import {
  provisionPluginRoute,
  provisionSigningKeyset,
  trustSignConfig,
  cleanupByPrefix,
  cleanupStale,
  decodeJwt,
  signJwt,
  type SigningKeyset,
} from "../../../helpers/trust-sign";

const PREFIX = uniquePrefix("trust-sign");

const JWKS_URI = "https://jwks.example.test/keys.json";

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

let keyset: SigningKeyset;

test.describe("trust-sign — response manifest signing", () => {
  test.beforeAll(async ({ request }) => {
    await cleanupStale(request, "trust-sign-");
    keyset = await provisionSigningKeyset(request, { prefix: PREFIX });
  });

  test.afterAll(async ({ request }) => {
    await cleanupByPrefix(request, PREFIX);
  });

  // [Verifies: trust-sign.response-manifest-signing.claims-echoed-from-inbound-token]
  test("echoes request_id/client_id/service_id/digest from the inbound token", async ({
    request,
  }) => {
    const { routePath } = await provisionPluginRoute(request, {
      prefix: PREFIX,
      config: trustSignConfig(keyset.keysetName, {
        direction: "response",
        jwks_uri: JWKS_URI,
        // distinct from the fixed inbound header name X-Edge-Token
        signature_header_key: "X-Response-Token",
      }),
    });

    const inboundClaims = {
      request_id: "inbound-req-id-1",
      client_id: "inbound-client",
      service_id: "inbound-service",
      digest: "sha-256=:aW5ib3VuZC1kaWdlc3Q=:",
    };
    const inboundToken = signJwt(inboundClaims, {
      alg: "RS256",
      kid: "rsa-2048",
      keyFile: "rsa-2048.pem",
    });

    const res = await proxyGet(request, routePath, {
      headers: { "X-Edge-Token": inboundToken },
    });
    expect(res.status()).toBe(200);

    const responseToken = res.headers()["x-response-token"];
    expect(responseToken).toBeTruthy();

    const { payload } = decodeJwt(responseToken);
    expect(payload.request_id).toBe(inboundClaims.request_id);
    expect(payload.client_id).toBe(inboundClaims.client_id);
    expect(payload.service_id).toBe(inboundClaims.service_id);
    expect(payload.digest).toBe(inboundClaims.digest);
    // jwks_uri comes from this plugin instance's config, not the inbound token
    expect(payload.jwks_uri).toBe(JWKS_URI);
  });

  // [Verifies: trust-sign.response-manifest-signing.unparseable-inbound-token-rejected]
  test("rejects an unparseable inbound X-Edge-Token with 403 Bad token", async ({
    request,
  }) => {
    const { routePath } = await provisionPluginRoute(request, {
      prefix: PREFIX,
      config: trustSignConfig(keyset.keysetName, {
        direction: "response",
        jwks_uri: JWKS_URI,
      }),
    });

    const res = await proxyGet(request, routePath, {
      headers: { "X-Edge-Token": "this-is-not-a-jwt" },
    });

    expect(res.status()).toBe(403);
    const body = await res.json();
    expect(body.message).toBe("Bad token");
    expect(body).toHaveProperty("error");
    // no signature header is set on the rejection
    expect(res.headers()["x-edge-token"]).toBeUndefined();
  });

  // [Verifies: trust-sign.response-manifest-signing.missing-inbound-token-bare-manifest]
  test("emits a bare manifest when the request has no X-Edge-Token", async ({
    request,
  }) => {
    const { routePath } = await provisionPluginRoute(request, {
      prefix: PREFIX,
      config: trustSignConfig(keyset.keysetName, {
        direction: "response",
        jwks_uri: JWKS_URI,
      }),
    });

    const res = await proxyGet(request, routePath);
    expect(res.status()).toBe(200);

    const responseToken = res.headers()["x-edge-token"];
    expect(responseToken).toBeTruthy();

    const { payload } = decodeJwt(responseToken);
    expect(payload.jwks_uri).toBe(JWKS_URI);
    expect(payload.jti).toMatch(UUID_RE);
    expect(typeof payload.iat).toBe("number");
    expect(payload).not.toHaveProperty("request_id");
    expect(payload).not.toHaveProperty("client_id");
    expect(payload).not.toHaveProperty("service_id");
    expect(payload).not.toHaveProperty("digest");
  });

  // [Verifies: trust-sign.response-manifest-signing.kong-generated-responses-are-signed]
  test("signs responses generated by Kong itself (request-termination)", async ({
    request,
  }) => {
    const { routePath } = await provisionPluginRoute(request, {
      prefix: PREFIX,
      config: trustSignConfig(keyset.keysetName, {
        direction: "response",
        jwks_uri: JWKS_URI,
      }),
      extraPlugins: [
        {
          name: "request-termination",
          config: { status_code: 503, message: "terminated by kong" },
        },
      ],
    });

    const res = await proxyGet(request, routePath);
    expect(res.status()).toBe(503); // upstream never reached

    // signature header set per the other response-direction scenarios
    // (no inbound token → bare manifest); no Content-Digest (no buffered
    // upstream body to digest)
    expect(res.headers()["content-digest"]).toBeUndefined();
    const responseToken = res.headers()["x-edge-token"];
    expect(responseToken).toBeTruthy();
    const { payload } = decodeJwt(responseToken);
    expect(payload.jwks_uri).toBe(JWKS_URI);
    expect(payload.jti).toMatch(UUID_RE);
    expect(typeof payload.iat).toBe("number");
    expect(payload).not.toHaveProperty("request_id");
  });
});
