set $session_storage             redis;
set $session_secret              '';
set $session_redis_prefix        sessions;
set $session_redis_host          kong-session-store;
set $session_redis_port          6379;
set $session_redis_uselocking    off;
set $session_redis_ssl           off;
set $session_redis_ssl_verify    off;
