FROM mcr.microsoft.com/playwright:v1.49.1-noble

RUN npx playwright install chrome

WORKDIR /e2e-playwright

# Copy package.json and package-lock.json
COPY . .

# Install dependencies
RUN npm ci

# Create directories for results and reports
RUN mkdir -p playwright-results playwright-reports

# --workers=1 : Run tests in a single worker - due to keycloak sessions
CMD ["npx", "playwright", "test", "--workers=1"]