ARG KONG_VERSION="2.8.5"
FROM kong:${KONG_VERSION}

USER root

RUN apk add --no-cache unzip

WORKDIR /build

COPY plugins/jwt-keycloak jwt-keycloak
RUN (cd jwt-keycloak && luarocks make)

COPY plugins/oidc oidc
RUN (cd oidc && luarocks make)

COPY plugins/oidc-consumer oidc-consumer
RUN (cd oidc-consumer && luarocks make)

USER kong

ENV KONG_PLUGINS="bundled, jwt-keycloak, oidc, oidc-consumer"
